version: "3.7"
services:
  react:
    image: node:latest
    command: npm start
    working_dir: /app
    volumes:
      - ./react:/app
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - NODE_ENV=development
    ports:
      - 3000:3000
  calends:
    build:
      context: ./calends
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./calends:/app
