version: "3.7"
services:
  react:
    image: node:latest
    command: npm start
    working_dir: /app
    volumes:
      - ./vite-react:/app
    environment:
      - HOST=0.0.0.0
      - PORT=5173
      - NODE_ENV=development
    ports:
      - 5173:5173
  calends:
    build:
      context: ./calends
      dockerfile: ./Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./calends:/app
